### ISSUE TITLE
a suggestion to the PointRenderer

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#68] opened 2016-03-22 09:27 UTC
```
using Android.Graphics;
using Mapsui.Providers;
using Mapsui.Styles;
using Point = Mapsui.Geometries.Point;
using Mapsui.Rendering.Android.ExtensionMethods;
using Bitmap = Android.Graphics.Bitmap;

namespace Mapsui.Rendering.Android
{
    static class PointRenderer
    {
        public static void Draw(Canvas canvas, IViewport viewport, IStyle style, IFeature feature)
        {
            var point = feature.Geometry as Point;
            var dest = viewport.WorldToScreen(point);
            var symbolSize = (float)SymbolStyle.DefaultHeight;
            var symbolType = SymbolType.Ellipse;

            var symbolStyle = style as SymbolStyle;
            if( (symbolStyle != null) && ( symbolType == SymbolType.Image ) )
            {
                if (symbolStyle.BitmapId >= 0)
                {
                    // Bitmap
                    if (!feature.RenderedGeometry.ContainsKey(style))
                        feature.RenderedGeometry[style] = 
                            BitmapFactory.DecodeStream(BitmapRegistry.Instance.Get(symbolStyle.BitmapId));
                    var bitmap = (Bitmap)feature.RenderedGeometry[style];
                    var halfWidth = bitmap.Width / 2;
                    var halfHeight = bitmap.Height / 2;
                    var dstRectForRender = new RectF((float)dest.X - halfWidth, (float)dest.Y - halfHeight, (float)dest.X + halfWidth, (float)dest.Y + halfHeight);
                    canvas.DrawBitmap(bitmap, null, dstRectForRender, null);
                    return;
                }
                symbolType = symbolStyle.SymbolType;
                if (symbolStyle.SymbolScale > 0) symbolSize = (float)symbolStyle.SymbolScale * symbolSize;
            }
            else
            {

                 // Drawing
                 var paints = style.ToAndroid();
                 if (symbolType == SymbolType.Ellipse)
                 {
                     foreach (var paint in paints)
                     {
                         canvas.DrawCircle((int)dest.X, (int)dest.Y, symbolSize, paint);
                         paint.Dispose();
                     }
                 }
                 else
                 {
                     foreach (var paint in paints)
                     {
                         canvas.DrawRect(-(float)SymbolStyle.DefaultWidth, (float)SymbolStyle.DefaultHeight, (float)SymbolStyle.DefaultWidth, -(float)SymbolStyle.DefaultHeight, paint);
                         paint.Dispose();
                     }
                 }
            }
        }
    }
}
```

**Comment by YordanYanakiev** [comment] 2016-03-22 09:31
```
using System;
using System.IO;

namespace Mapsui.Styles
{
    public enum SymbolType
    {
        Ellipse,
        Rectangle,
        Image
    }

    public enum UnitType
    {
        Pixel,
        WorldUnit
    }

    public class SymbolStyle : VectorStyle
    {
        private Bitmap _bitmap;

        public SymbolStyle()
        {
            SymbolOffset = new Offset();
            SymbolScale = 1f;
            Opacity = 1f;
            BitmapId = -1;
        }

        /// <summary>
        /// Symbol used for rendering points
        /// </summary>
        [Obsolete("use BitmapID and BitmapRegistry instead")]
        public Bitmap Symbol
        {
            get { return _bitmap;  }
            set
            {
                _bitmap = value;
                // The code below is to make sure existing bitmap initialization still works (for now)
                if (_bitmap != null && _bitmap.Data != null) BitmapId = BitmapRegistry.Instance.Register(_bitmap.Data);
                if (_bitmap != null) _bitmap.BitmapDataAddedEventHandler += (sender, args) => Register(_bitmap.Data);
            }
        }

        private void Register(Stream data)
        {
            if (data != null) BitmapId = BitmapRegistry.Instance.Register(data);
        }

        /// <summary>
        /// This identifies bitmap in the BitmapRegistry. 
        /// </summary>
        public int BitmapId { get; set; }

        /// <summary>
        /// Scale of the symbol (defaults to 1)
        /// </summary>
        /// <remarks>
        /// Setting the symbolscale to '2.0' doubles the size of the symbol, where a scale of 0.5 makes the scale half the size of the original image
        /// </remarks>
        public double SymbolScale { get; set; }

        /// <summary>
        /// Gets or sets the offset in pixels of the symbol.
        /// </summary>
        /// <remarks>
        /// The symbol offset is scaled with the <see cref="SymbolScale"/> property and refers to the offset af <see cref="SymbolScale"/>=1.0.
        /// </remarks>
        public Offset SymbolOffset { get; set; }

        /// <summary>
        /// Gets or sets the rotation of the symbol in degrees (clockwise is positive)
        /// </summary>
        public double SymbolRotation { get; set; }

        public UnitType UnitType { get; set; }

        public SymbolType SymbolType { get; set; }

        public double Opacity { get; set; }
        
        public static double DefaultWidth = 32;

        public static double DefaultHeight = 32;

        
        public override bool Equals(object obj)
        {
            if (!(obj is SymbolStyle))
            {
                return false;
            }
            return Equals((SymbolStyle)obj);
        }

        public bool Equals(SymbolStyle symbolStyle)
        {
            if (!base.Equals(symbolStyle))
            {
                return false;
            }

            if (BitmapId != symbolStyle.BitmapId)
            {
                return false;
            }

            if (!SymbolScale.Equals(SymbolScale))
            {
                return false;
            }

            if ((SymbolOffset == null) ^ (symbolStyle.SymbolOffset == null))
            {
                return false;
            }

            if ((SymbolOffset != null) && (!SymbolOffset.Equals(symbolStyle.SymbolOffset)))
            {
                return false;
            }

            if (Math.Abs(SymbolRotation - symbolStyle.SymbolRotation) > Utilities.Constants.Epsilon)
            {
                return false;
            }

            if (UnitType != symbolStyle.UnitType)
            {
                return false;
            }

            if (SymbolType != symbolStyle.SymbolType)
            {
                return false;
            }

            if (Math.Abs(Opacity - symbolStyle.Opacity) > Utilities.Constants.Epsilon)
            {
                return false;
            }
            
            return true;
        }

        public override int GetHashCode()
        {
            return BitmapId.GetHashCode() ^ 
                SymbolScale.GetHashCode() ^ SymbolOffset.GetHashCode() ^
                SymbolRotation.GetHashCode() ^ UnitType.GetHashCode() ^ SymbolType.GetHashCode() ^
                Opacity.GetHashCode() ^ base.GetHashCode();
        }

        public static bool operator ==(SymbolStyle symbolStyle1, SymbolStyle symbolStyle2)
        {
            return Equals(symbolStyle1, symbolStyle2);
        }

        public static bool operator !=(SymbolStyle symbolStyle1, SymbolStyle symbolStyle2)
        {
            return !Equals(symbolStyle1, symbolStyle2);
        }

            }
}
```

**Comment by YordanYanakiev** [comment] 2016-03-22 14:15
The issue i am trying to prevent is drawing a small white square behind the marker.

**Comment by pauldendulk** [comment] 2016-03-28 10:37
When do you see this white square? How can I reproduce it?

**Comment by YordanYanakiev** [comment] 2016-03-28 11:22
I am seen the white squares when the image of the marker is below 32 pixels.
I found a solution to set in the SDK 


        public static double DefaultWidth = 2; // 32
        public static double DefaultHeight = 2; // 32

**Comment by pauldendulk** [comment] 2016-03-28 13:07
When I use a symbol image of 1x1 in the random point layer of Mapsui.Samples.Android I don't see such a white square in the background.

Mapsui can have symbols on layers but also on features. If you set the symbol on the feature the default symbol on the layer still exists. Perhaps you need to just set the layer style to null. 
```
layer.Style = null
```

**Comment by YordanYanakiev** [comment] 2016-04-07 11:35
I've setup the result layer.Style to null, there is no change.
The bug goes even bigger with a bit older CPU architecture like Mediatek's MT6577 - the result is completely white markers.

**Comment by pauldendulk** [comment] 2016-04-09 20:28
I tried to reproduce it today but could not. Above you post code on Mapsui.Rendering.Android. Is this what is used. Do you use the MapView? The new MapControl use Mapsui.Rendering.OpenTK-A.

How do you define your layers and the styles on them? Could you try to reproduce the problem with a small modification of the current Android sample. I just changed to sample to use MapView.

**Comment by pauldendulk** [comment] 2016-10-17 06:23
I am closing this issue as 'can't reproduce'. Keep in mind that it is actually possible to draw multiple styles on top of each other. This can be through multiple styles on a feature and a style on the layer. All of these are drawn, where the feature has priority.

**Closed by pauldendulk** 2016-10-17 06:23 UTC
