### ISSUE TITLE
1.3.2 breaks Android taps on feature icons

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#305] opened 2018-02-03 16:54 UTC
It seems like the latest beta updates are breaking the ability to click on icons on Android. Many users report that they are not able to open the popup dialogs correctly since the last update which include 1.3.2-beta2 on Android (they appear after a double tap on a feature). I notice the same problem in the debugger that the click is often not registered correctly. 

It works on iOS pretty well with 1.3.2-beta2 but Android seems to be broken with it.

**Comment by radderz** [comment] 2018-02-04 19:35
I'll have a look as I used the guesture recognizer for it, its supposed to use a confirmed single tap for the info. As I was planning to add double tap to zoom which I have implemented for my own project.

**Comment by radderz** [comment] 2018-02-05 02:06
@Sebastian1989101 - Info is invoked on a guaranteed single tap in android, on ios, if you double tap it will call the invoke info twice.

**Comment by Sebastian1989101** [comment] 2018-02-05 07:19
@radderz that is exactly what I expect and what happens with Mapsui 1.3.1. But with 1.3.2 on Android the Info event is not invoked properly. Only after a few action on the map it might be invoked. It starts working again as soon as I downgrade to 1.3.1 without changing anything else. So it is diffenetly a problem with 1.3.2 of Mapsui.

**Comment by radderz** [comment] 2018-02-05 07:26
We use 1.3.2 beta 2 and touch interactions are reliable. Which beta are you using?

**Comment by Sebastian1989101** [comment] 2018-02-05 07:33
@radderz Beta 2 and it is unuseable on Android until you pan around or zoom. Than it works for a few clicks. As already mentioned it works as soon as I downgrade to 1.3.1 without any problems. Also 1.3.2 works on iOS without any problems.

**Comment by Sebastian1989101** [comment] 2018-02-05 07:54
The double tap is implemented within in my app. But the event is not even called once (don't matter how often I tap the feature icon). My guess is that the hitbox for the features is broken because it works sometimes (in my case ~20%). 

After the first call I store the feature identifier and if the same comes a 2nd time I open a Popup. That is what I mean with double tap. But currently the event is not invoked with 1.3.2. Maybe @pauldendulk has an idea what changed between 1.3.1 and 1.3.2 what could explain this different behaviour.

**Comment by radderz** [comment] 2018-02-05 08:04
If you are hoping for double tap behaviour it won't work that way, I wrote the behaviour. It is only going to call the info event for a single tap. A double tap will not call the info twice like it used to. There is a pull request to enable a double tap type logic but the way you have it implemented will not work with beta 2 or the next version unless a change is made to the way the info event works. You are using the feature in an I intended way. It probably would work for double taps with a time gap between them currently. 

I suggest the info layer event to be invoked with the number of taps that caused the invoke to occur in the args so that you don't need to do logic like that and so you can handle double tap the way you are wanting to use it.

See PR #307

**Comment by radderz** [comment] 2018-02-05 08:07
Are you able to accept the tap on the first tap to test?

**Comment by Sebastian1989101** [comment] 2018-02-05 08:18
If this is the case, than 1.3.2 is unusable for me until a double tap behaviour is added. Also it works different on iOS and Android in this case which is a very bad way because nobody would expect it to act differnt on two platforms.

**Comment by radderz** [comment] 2018-02-05 08:34
It acted different on all the other platforms prior. There was no consistency between uwp, ios, android and wpf. For info it would be invoked even on touch up from a pinch which makes no sense.

For iOS it was incorrectly done but the single tap will now not call the single tap on a double tap like in the 1.3.2 b2.

I'll add the number of taps to the args, you'll only get a single info call back, but with the number of taps inside the args.

**Comment by Sebastian1989101** [comment] 2018-02-05 09:13
The pinch resulting in the info event was the reason why I added this "double tap" in the first place. In the 1.3.2 beta 2 it still works this way on iOS but as you already know not on Android. It would be better if it at least behave the same on all the platforms. Espacially for such events which may result in some interaction like popup dialogs. 

If it is safe that the pinch and zoom no longer triggers the info event, I would prefer a single tap anyway - at least for my current apps with Mapsui. Otherwise it would be nice to know if the same entry was tapped two times or not. The problem there might be that sometimes multiple icons overlap - what happens in this case?

**Comment by charlenni** [comment] 2018-02-05 10:40
With overlapping icons: I had the same problem with widgets. In this case, I use to check the widget in reverse order, so that the last drawn (top most on screen) is the first to check.

**Comment by radderz** [comment] 2018-02-06 19:37
Hi Sebastian, yes it is safe now to use single tap. I did the change exectly for the pan and zoom issues around touch up. you can now assume a single tap is a real single tap and not a zoom/pan. 

@charlenni am I missing something? are you talking about the other issue around iteration order of widgets?

**Comment by radderz** [comment] 2018-02-06 19:38
@Sebastian1989101 - The pull request that will send double taps just like single taps (1 event only for both types of instance. i.e double tap will result in a single event being fired has been merged. However I haven't added the number of taps to the args yet.)

**Comment by radderz** [comment] 2018-02-06 20:25
@Sebastian1989101 see #309

**Comment by charlenni** [comment] 2018-02-07 05:41
It belongs to “The problem there might be that sometimes multiple icons overlap - what happens in this case?”

**Comment by pauldendulk** [comment] 2018-02-07 08:00
About overlapping icons. The logic should be that it returns the top one and ignores the features below that. 

For widgets this should be the same but apparently there the widget in de background was returned. I think this was fixed with charlenni's pull request. Is this correct @charlenni?

**Comment by pauldendulk** [comment] 2018-02-07 08:03
@Sebastian1989101 So the conclusion is that your solution was a workaround for a broken implementation. With a fix in that implementation you will have to change your implementation and expect no further impediments, correct?

**Comment by Sebastian1989101** [comment] 2018-02-07 08:41
@pauldendulk yes. I just did not expect a change in this behavoir because it did not change on iOS as well. While the double tap has still be called the info event twice on iOS I didn't notice any difference but on Android it was not called twice. 

Still would be great to have the option for single tap, double tap and long tap because all three could trigger different things within the app. But maybe this is more for a specific feature request.

**Comment by pauldendulk** [comment] 2018-02-07 08:51
In 1.3.2-beta4 work has been done on double tap. InfoEventArgs will have a NumTabs. It is now published: 
https://www.nuget.org/packages/Mapsui/

**Comment by charlenni** [comment] 2018-02-07 10:06
@pauldendulk: Yes this is correct. I used Widgets.Reverse for the foreach Loop. But this wouldn’t work for Features, because there are many more of them. And Reverse creates a new list in memory which could produce problems with memory.

**Comment by pauldendulk** [comment] 2018-02-07 10:54
Is there an issue for Icons? To my knowledge this works correctly. It first selects all features for which the click position is in the boundingbox, and reverses only those features (will be 1 most of the time).

**Comment by charlenni** [comment] 2018-02-07 14:19
Yes, it seems to work correct. In InfoHelper you reverse Layers and than use LastOrDefault to get the Feature.

But the comment in Map.InvokeInfo is misleading. Perhaps you could correct it.

**Comment by radderz** [comment] 2018-02-07 21:07
@Sebastian1989101 will close this as you now have the number of taps as a property of the args in 1.3.2-beta4 you should mark handled as true if you use it so that future changes that do different behavior where handled is false like double click to zoom don't impact you.

**Closed by radderz** 2018-02-07 21:07 UTC
Labels: bug
