### ISSUE TITLE
Cannot access a disposed object (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#272] opened 2018-01-04 22:49 UTC
In my latest project with Mapsui I have 17 different game maps within my app. If I now do a lot of navigation (keep each map in the navigation stack) and than navigate back through the navigation stack at some point a "Cannot access a disposed object."-Exception comes up from the iOS MapControl. I did not test Android yet. 

Currently it seems like if I do this: 
Navigate to Map 1 - Navigate to some Checklist - Navigate to Map 2 - Navigate Back - Navigate Back (Exception now when Map 1 should be loaded again). Is there some static stuff within MapControl which crash now because Map 2 triggers a dispose somewhere within the MapControl?

**Comment by pauldendulk** [comment] 2018-01-05 08:00
Could you try 
`mapControl.Map = null; `
Which is a workaround that helped here:
https://github.com/pauldendulk/Mapsui/issues/271

**Comment by Sebastian1989101** [comment] 2018-01-05 11:26
Just tried it but the exception happens before the Dispose of my Forms Wrapper happens.

**Comment by pauldendulk** [comment] 2018-01-06 07:56
Do you have a stacktrace?

**Comment by pauldendulk** [comment] 2018-01-06 07:57
Are there any other Dispose calls in your code? 
If you temporarily remove the Dispose call in your iOS renderer, does this prevent the exception? (this is not a solution, just to diagnose).

**Comment by Sebastian1989101** [comment] 2018-01-06 15:23
There is no dispose within the renderer so I guess the GC is trying to remove the no longer in use page from the memory which include the map. Here are the 2 available stack traces (C# and native iOS): 

```
Cannot access a disposed object.
Object name: 'MapControl'.
  at Foundation.NSObject.get_SuperHandle () [0x00015] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/Foundation/NSObject2.cs:416 
  at UIKit.UIView.SetNeedsDisplay () [0x0002a] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/build/ios/native/UIKit/UIView.g.cs:1697 
  at Mapsui.UI.iOS.MapControl.RefreshGraphics () [0x00000] in <582bf1dbd0bb49e3a7e65e8d5203a079>:0 
  at Mapsui.UI.iOS.MapControl+<>c__DisplayClass30_0.<MapDataChanged>b__0 () [0x000de] in <582bf1dbd0bb49e3a7e65e8d5203a079>:0 
  at CoreFoundation.DispatchQueue.static_dispatcher_to_managed (System.IntPtr context) [0x0003d] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/CoreFoundation/Dispatch.cs:343 
  at (wrapper native-to-managed) CoreFoundation.DispatchQueue:static_dispatcher_to_managed (intptr)
--- End of stack trac
e from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at OdysseyCompanion.iOS.Application.Main (System.String[] args) [0x00001] in H:\Repos\OdysseyCompanion\OdysseyCompanion\OdysseyCompanion\OdysseyCompanion.iOS\Main.cs:13 
2018-01-06 16:20:41.467 OdysseyCompanion[14513:546590] Unhandled managed exception:
Cannot access a disposed object.
Object name: 'MapControl'. (System.ObjectDisposedException)
  at Foundation.NSObject.get_SuperHandle () [0x00015] in /Users/builder/data/lanes/56
65/6857dfcc/source/xamarin-macios/src/Foundation/NSObject2.cs:416 
  at UIKit.UIView.SetNeedsDisplay () [0x0002a] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/build/ios/native/UIKit/UIView.g.cs:1697 
  at Mapsui.UI.iOS.MapControl.RefreshGraphics () [0x00000] in <582bf1dbd0bb49e3a7e65e8d5203a079>:0 
  at Mapsui.UI.iOS.MapControl+<>c__DisplayClass30_0.<MapDataChanged>b__0 () [0x000de] in <582bf1dbd0bb49e3a7e65e8d5203a079>:0 
  at CoreFoundation.DispatchQueue.static_dispatcher_to_managed (System.IntPtr context) [0x0003d] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/CoreFoundation/Dispatch.cs:343 
  at (wrapper native-to-managed) CoreFoundation.DispatchQueue:static_dispatcher_to_managed (intptr)
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delega
te) [0x00005] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at OdysseyCompanion.iOS.Application.Main (System.String[] args) [0x00001] in H:\Repos\OdysseyCompanion\OdysseyCompanion\OdysseyCompanion\OdysseyCompanion.iOS\Main.cs:13 
```

```
critical: 
Native stacktrace:
The thread 0xf has exited with code 0 (0x0).
2018-01-06 16:20:41.505 OdysseyCompanion[14513:546590] critical: 	0   Mono                                0x000000010fd580e4 mono_handle_native_crash + 244
2018-01-06 16:20:41.505 OdysseyCompanion[14513:546590] critical: 	1   libsystem_platform.dylib            0x0000000119dcbf5a _sigtramp + 26
2018-01-06 16:20:41.505 OdysseyCompanion[14513:546590] critical: 	2   ???                                 0x0000ffff00001fbf 0x0 + 281470681751487
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	3   libsystem_c.dylib                   0x0000000119a610eb abort + 127
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	4   OdysseyCompanion                    0x000000010fae15df xamarin_unhandled_exception_handler + 47
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	5   Mono                                0x000000010fdf7c04 mono_invoke_unhandled_exception_hook + 148
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	6   Mono                                0x000000010fd57c0d mono_handle_exception_internal + 5805
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	7   Mono                             
   0x000000010fd56558 mono_handle_exception + 24
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	8   Mono                                0x000000010fdbb37f mono_amd64_throw_exception + 143
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	9   ???                                 0x000000012d80fae7 0x0 + 5058394855
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	10  OdysseyCompanion                    0x000000010fae11d7 xamarin_process_managed_exception_gchandle + 55
2018-01-06 16:20:41.506 OdysseyCompanion[14513:546590] critical: 	11  OdysseyCompanion                    0x000000010fae1193 xamarin_ftnptr_exception_handler + 19
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	12  ???                                 0x000000013826df03 0x0 + 5237038851
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	13  libdispatch.dylib                   0x000000011991a1ba _dispatch_client_callout + 8
2018-01-06 16:20:41.507 OdysseyCompanion[14
513:546590] critical: 	14  libdispatch.dylib                   0x00000001199243a4 _dispatch_main_queue_callback_4CF + 1260
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	15  CoreFoundation                      0x0000000117d45e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	16  CoreFoundation                      0x0000000117d0a462 __CFRunLoopRun + 2402
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	17  CoreFoundation                      0x0000000117d09889 CFRunLoopRunSpecific + 409
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	18  GraphicsServices                    0x000000011ac709c6 GSEventRunModal + 62
2018-01-06 16:20:41.507 OdysseyCompanion[14513:546590] critical: 	19  UIKit                               0x000000011038c5d6 UIApplicationMain + 159
2018-01-06 16:20:41.508 OdysseyCompanion[14513:546590] critical: 	20  ???                                 0x000000012fe67ae8 0x
0 + 5098601192
2018-01-06 16:20:41.508 OdysseyCompanion[14513:546590] critical: 	21  ???                                 0x000000012fe67713 0x0 + 5098600211
2018-01-06 16:20:41.508 OdysseyCompanion[14513:546590] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
The app has been terminated.
```

**Comment by pauldendulk** [comment] 2018-01-06 18:09
The really looks a lot like the problem described in the other issue I pointed to. 

Reading from the top down:
- It is the MapControl that is not disposed.
- There is an attempt to cal UIView.SetNeedsDisplay 
- There is an attempt to call MapControl.RefreshData
- This is triggered from MapDataChanged, which is a event handler called from the Map

The third step should be preventable by setting the MapControl.Map to nulll. Since the Map has a pointer to the MapControl it can not be disposed by GC without an explicit dispose called (or triggered) in the client code. Perhaps dispose is called by your MVVM framework.

As mentioned in the other thread I will remove the event handlers in the dispose, and this should fit it. But you should be able to work around it.

**Comment by Sebastian1989101** [comment] 2018-01-06 18:13
The problem in my current structure is, that I have no real hard access to the native iOS control because it is wrapped within the renderer. And sadly there is no call before this happens (or at least I did not found it yet).

**Comment by pauldendulk** [comment] 2018-01-06 19:22
Are you using a nuget package of you native ios renderer?

**Comment by Sebastian1989101** [comment] 2018-01-06 19:23
No but it is the very same as in the OpenGeoDB app. I will check if there is some method triggerd right before the exception happens.

**Comment by pauldendulk** [comment] 2018-01-06 19:39
Try this: https://www.nuget.org/packages/Mapsui/1.3.1-beta1

**Comment by Sebastian1989101** [comment] 2018-01-06 20:57
Just tested with 1.3.1-beta1 but the problem still remains.

**Comment by pauldendulk** [comment] 2018-01-06 22:37
Could you try a `mapControl.Map.ClearCache()` before reassigning the Map to the MapControl?

Does this problem occur every time you try to reproduce it? Or does it seem the timing matters?

**Comment by Sebastian1989101** [comment] 2018-01-06 22:57
Seems like it happens not every time but sometimes. Maybe it is a specific timespan between the problem and the first dispose or something like that. I will try the clear cache thing.

**Comment by pauldendulk** [comment] 2018-01-07 07:29
The  exception is on DataChanged. If  you wait longer between actions the map should be able to load fully. If you return after the map is fully loaded no exception should occur. Could you check? Just to diagnose.

**Comment by Sebastian1989101** [comment] 2018-01-07 18:23
Seems to work if I wait longer. But I guess this is no solution for the user. Except I use a async thread which waits a few seconds until it removes the event registration (before it does not dispose the objects I guess).

**Comment by pauldendulk** [comment] 2018-01-08 17:23
No, it is just to diagnose, as I mentioned. This does indicate it is indeed related to the DataChanged event handler and not something different altogether. The more surprised I am the 1.3.1-beta1 patch did not fix it. 

Could you check again if the update of that version was done for all of your projects? Or could there perhaps be another problem on your side?

**Comment by Sebastian1989101** [comment] 2018-01-13 01:57
Just installed 1.3.1-beta3, cleaned everything up and rebuilt the solution. The exception now takes a lot more and a lot quicker back navigation to happen but after 27 very quick back navigations I got this: https://puu.sh/z0kkm/162f5447b6.png - seems to be the same exception?

**Comment by pauldendulk** [comment] 2018-01-13 07:11
Thanks. Yes. same exception. That it still occurs in rare cases could be related to threading. Perhaps I should use a 'disposed' field to check in event handler callbacks. https://stackoverflow.com/questions/5024883/thread-safety-of-dispose-methods

**Comment by pauldendulk** [comment] 2018-01-13 15:32
In MapDataChanged I now catch and write to log. If it is catching the dispose exception this will have no effect on the user.

**Closed by pauldendulk** 2018-01-13 15:32 UTC
Labels: possible bug

**Comment by tizumiZoo** [comment] 2018-01-25 02:41
I encountered the same issue on iOS (emulator) by disposing and creating map repeatedly. Not all the time but at a certain timing. Judging from the MapControl class for iOS, maybe because MapDataChanged handler dispatch asyn action which calls RefreshGraphics(), and if at a weird timing MapControl has been disposed, it seems to crash. Do you need to re-throw the exception caught within MapDataChanged method?

For now, I am probably going to add a delay when disposing

**Comment by pauldendulk** [comment] 2018-01-25 05:51
@tizumiZoo Which version do you use?

**Comment by tizumiZoo** [comment] 2018-01-25 05:53
ver. 1.3.1

**Comment by pauldendulk** [comment] 2018-01-25 06:11
@tizumiZoo oh, I see what you mean, there should be no re throw in MapDataChanged. That is at least an improvement improvement.

What seems to be happening is that first MapDataChanged is called. While that processing is running Dispose is called (which removes the MapDataChanged event handler but this is too late). MapDataChanged continues and crashes.

I could (and I guess I have to) fix this by checking a disposed boolean in MapDataChanged when it is back on the main thread. But if this is the best solution this would mean all classes that have a Dispose method and could be called async should have to deal with this. Is this a common pattern? There are probably people who have worked this all out.

**Comment by tizumiZoo** [comment] 2018-01-25 06:51
Yes, (maybe) at least removing throw in MapDataChanged in iOS MapControl prevents from crashing (?). And probably good idea to check for disposed flag but a thing is if the action has been already queued in iOS MapControl.MapDataChanged(), it may be hard to totally prevent by checking the flag, as not sure which timing context change??

A thing is, we do
- Use TileLayer with our custom tile source to fetch tile from a data source
- Use Xamarin Form and map is one of pages (using custom renderer), and when page is popped out, the custom render is disposed (which dispose MapControl)

At the moment, no way to guarantee that fetching in tile layer has been stopped and no pending action/tasks from the tile fetching background worker. 

This may be still caller's (my) responsibility to put a enough interval between creation and disposal of the map object...

**Comment by pauldendulk** [comment] 2018-01-29 20:59
@tizumiZoo I removed the rethrow in the 1.3.2-beta2 release. https://www.nuget.org/packages/Mapsui/1.3.2-beta2

**Comment by pauldendulk** [comment] 2018-01-29 20:59
Thanks for noticing that!

**Comment by tizumiZoo** [comment] 2018-02-05 05:09
No problem. 

Could you possibly make changes in UWP MapControl.MapDataChanged? Maybe try-catch as in iOS MapControl (maybe specifically around RegreshGraphics()). 

Having a crash on a particular Windows10 device but not really able to identify where is the crash point.

**Comment by tkopton** [comment] 2018-10-04 15:54
Occasionally I am experiencing "System.ObjectDisposedException: Cannot access a disposed object." while leaving the ContentPage showing the map. MapsUi 1.4.7

Is there anything I can do to prevent the app from crashing?

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MapControl'.
  at Foundation.NSObject.get_SuperHandle () [0x00012] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSObject2.cs:449
  at UIKit.UIView.SetNeedsDisplay () [0x00023] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIView.g.cs:1722
  at Mapsui.UI.iOS.MapControl.<RefreshGraphics>b__27_0 () [0x00000] in <c5bd075791cf45e999643c33be9edffc>:0
  at CoreFoundation.DispatchQueue.static_dispatcher_to_managed (System.IntPtr context) [0x00038] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/CoreFoundation/Dispatch.cs:344
  at at (wrapper native-to-managed) CoreFoundation.DispatchQueue.static_dispatcher_to_managed(intptr)
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at app_test_01.iOS.Application.Main (System.String[] args) [0x00001] in /Users/tkopton/Projects/app_test_01/app_test_01.iOS/Main.cs:17

**Comment by pauldendulk** [comment] 2018-10-04 17:12
I did investigate this before. When you navigate away in forms the old activity is disposed. But in the mapsui forms implementation the disposed form is accessed through the message center.  https://github.com/Mapsui/Mapsui/issues/433#issuecomment-395956306

So, in forms don't call a RefreshGraphics from the message center.

**Comment by pauldendulk** [comment] 2018-10-04 17:13
I conclude this is not a bug in Mapsui. Not in 1.4.7 or any 2.0 beta.

**Comment by tkopton** [comment] 2018-10-04 17:50
OK, this will be challenging for me, just started with C# and Xamarin few weeks ago for my university project.
My ContentPage showing the MapsUI map has a public method which does changes to the map, like NavigateTo. This method is being called from another classes and I assume that the calling that method causes the issue when dispose was already fired.
Since I was not able to use MVVM, I will need something else.
How to do this "don't call a RefreshGraphics from the message center.!"?

Many thanks.

**Comment by pauldendulk** [comment] 2018-10-04 17:53
This is how you implement your xamarin forms map component.

**Comment by tkopton** [comment] 2018-10-04 18:09
Sorry, but I still don't get it.
What if I make my:

```
public void RefreshMap()
        {
            // todo:
            var centerOfPlane = new Point(_vm.PlaneData.LonDeg, _vm.PlaneData.LatDeg);
            var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(centerOfPlane.X, centerOfPlane.Y);
            mapControl.NativeMap.NavigateTo(sphericalMercatorCoordinate);

            var planeLayer = mapControl.NativeMap.Layers[3];
            mapControl.NativeMap.Layers.Remove(planeLayer);
            planeLayer = null;
            planeLayer = GeneratePlane();
            mapControl.NativeMap.Layers.Add(planeLayer);

            float rotation = _vm.PlaneData.HdingMag;
            mapControl.NativeMap.RotateTo(-rotation);
        }
```

private and call it from inside the ContentPage using a timer, the model, which provides the data is always up-to-date.

**Comment by tkopton** [comment] 2018-10-04 18:57
Timer inside the ContentPage which displays the Map does not help - same issue. Maybe a simple ContentPage != null will help... checking
