### ISSUE TITLE
Version 1.1.1 - Feature on click event is always NULL (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#236] opened 2017-10-22 00:49 UTC
As already mentioned per mail, the Feature parameter of the Info-EventArgs is always NULL on iOS in the latest Mapsui version.

**Comment by pauldendulk** [comment] 2017-11-01 21:56
Looks like this is a duplicate of #233.

**Closed by pauldendulk** 2017-11-01 21:56 UTC
