### ISSUE TITLE
UWP app map render problem

### ISSUE THREAD

**Issue by Yurijj** [pauldendulk/Mapsui#76] opened 2016-06-13 19:36 UTC
Hello,

I'm developing an application under UWP platform and using MapsUI library. In a special case we have an issue with "white triangles" on the map, in case if "Me" layer Enabled is true.

Trying to debug code in Mapsui.Rendering.XamlRendering-W8.dll!Mapsui.Rendering.XamlRendering.MapRenderer.Render(Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable<Mapsui.Layers.ILayer> layers),C#.

My question is do you have any idea why I can get this rendering issue and corrupted maps view (more details on attached screenshot)?

![map_rendering_00](https://cloud.githubusercontent.com/assets/2151351/16020621/99e4e8e0-31b7-11e6-97d8-06977882750d.png)

**Comment by pauldendulk** [comment] 2016-06-13 20:14
That is a pretty weird effect. I have not seen this myself. It is normal when the me-layer is off? The me-layer is your personal location? Is it independent of the zoom level?

Issues that I have seen with UWP rendering were when zoomed-in close.

**Comment by Yurijj** [comment] 2016-06-13 20:17
Me layer is my personal location. It is can be on or off. And each time when I return to the ON option of this layer, I observe this "white triangles". It is also independent from zoom level, when I change it, maps redraw and I have this issue again with a different map scale. Any idea with what I can start?

**Comment by pauldendulk** [comment] 2016-06-13 21:00
I don't have a clue yet. It looks like the tiles are not drawn correctly. But why is this cause by the me layer. Do you have the same problem if you try another background layer? What if you put an empty layer on top of the tile layers? What if you then add one feature to that layer? Are you sure there are only two layers? Could you check the layer count in debug mode?

**Comment by Yurijj** [comment] 2016-06-14 08:26
I have 3 layes in total. Layer1, MeLayer, Layer2. I haven't any problems with other background layer. Now playing with dding features to layers. Still debugging... Strange issue.

**Comment by pauldendulk** [comment] 2016-09-23 16:59
I am closing this issue because I cannot reproduce it. If you have a minimal app to reproduce it I will take a look. You could also try the new UWP version. New PCLs used in Mapsui.Samples.Uwp

**Closed by pauldendulk** 2016-09-23 16:59 UTC

**Comment by Yurijj** [comment] 2016-09-26 09:05
Thanks. I'll try a Mapsui.Samples.Uwp Sample.
