### ISSUE TITLE
How to work with local tile server with Mapsui

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#106] opened 2016-11-24 08:01 UTC
Maybe this is not the best place to ask for a tutorial. But We want to use offline tiles.
Any hints of how this can be done?? So we want to download a bunch of tiles (from openstreetmap for example) and then work with them in local offline mode.

**Comment by pauldendulk** [comment] 2016-11-24 08:37
In your title you mention 'tile server', do you actually want some kind of server? Otherwise I would go for a sqlite database. BruTile has a sample for this. You could take a look at the MbTiles sample in Itinero.UI: https://github.com/itinero/ui/blob/master/samples/Itinero.Code.Samples/MbTilesSample.cs

**Comment by 88madri** [comment] 2016-11-24 14:00
Thanks. I´ve tried with that example on my project and works perfect. But for example with this kind of mbtiles does not work. ( Maybe something with the zoom levels ??) This was created by Maperitive, and other apps like MapTile can open it...

https://drive.google.com/file/d/0B9K8dVGzWpH1b0lBSXkzVTNET2s/view?usp=sharing

**Comment by 88madri** [comment] 2016-11-29 08:15
I don't know what is really happening here. Finally I could open the previous mbtile file. But only if I apply a previous zoom level (My map start with a OSM layer) and pan to a certain zone then the mbtiles loads perfect. Is strange becouse I clear the previous OSM layer before load the Tile Layer with MBtileSource...
In other cases such when previous layer (OSM) is on default zoom level the memory begins to increase a lot and finally the mbTiles does not show...
.

**Comment by pauldendulk** [comment] 2016-11-29 20:20
Thanks for adding the mbtiles file. 

I used DBBrowser for SQLite to open the map.mbtiles file. It has an option to show the blobs as images which is nice. The images are there and seem okay:
![image](https://cloud.githubusercontent.com/assets/963462/20726590/8eb268b4-b676-11e6-9d7c-78cdf9a30519.png)



Then I used BruTiles.Samples.MbTiles to zoom to the tiles available in the .mbtiles and they do indeed show in the application but not as you would expect. I looks like the y-axis is inverted:
![image](https://cloud.githubusercontent.com/assets/963462/20726519/3d27d8e4-b676-11e6-9ff0-5f1172515d68.png)

**Comment by pauldendulk** [comment] 2016-11-29 20:21
ah yes, when I user Axis.TMS by hacking the samples code I get a proper map, and it zooms to the right extent at load:
![image](https://cloud.githubusercontent.com/assets/963462/20726962/f7b55f8c-b677-11e6-8a5c-8c78c1a32766.png)

**Comment by pauldendulk** [comment] 2016-11-29 20:40
It turned out the axis order should have been TMS in that sample. It fixed this in this commit https://github.com/BruTile/BruTile/commit/a5ccbb552b14a661ee6ad2a4b44f1959a978cb93. It was TMS in an another case which was used in my sample mbtiles files.

So this solved the problem of the BruTile mbtiles viewer. Now can you get this to work in Mapsui?

**Comment by 88madri** [comment] 2016-11-30 08:17
Well I changed my Brutile.dll and Brutile.MbTiles.dll and my project and I still have the same problem with that .mbTile file. 

Only works if previously I zoom on my standar OSM Tile Layer, then with a zoom level, I clear this OSM Tile Layer and load the .mbTile layer the map shows correctly. But if I don't do this, the app becomes unresponsive and memory begins to increase a lot.

If I use other mbTile with zoom level from 0 like this.

https://drive.google.com/file/d/0B9K8dVGzWpH1ZENaTTRtUTJucVE/view?usp=sharing

Then my app works perfect...

**Comment by pauldendulk** [comment] 2016-12-01 14:06
okay, I will test it myself. The problem that I fixed earlier was because map.mbtiles did not have resolutions specified. Perhaps this is also causing problems here. 

I will have no time for this until [sinterklaas](https://es.wikipedia.org/wiki/Fiesta_de_San_Nicol%C3%A1s_(Pa%C3%ADses_Bajos)) (he's from Spain too!)

**Comment by pauldendulk** [comment] 2017-01-10 13:59
I think this is a bug that occurs if the the tile schema specifies no resolutions. Should be fixed in [BruTile](https://github.com/BruTile/BruTile)

**Comment by pauldendulk** [comment] 2017-03-31 19:27
The fix affects performance. In my test the application was slower without the fix but still workable. It is clearly faster with the fix.

**Closed by pauldendulk** 2017-03-31 19:27 UTC
Labels: bug

**Comment by 88madri** [comment] 2017-03-31 19:30
What Fix do you refer to?? Do you update brutile??

**Comment by pauldendulk** [comment] 2017-03-31 22:36
This part was fixed:
> the app becomes unresponsive and memory begins to increase a lot.
The missing tiles are not fetched again and again.

This is done with this commit:
https://github.com/pauldendulk/Mapsui/commit/61a6a70bef6fe9fe7cbe7cf470fa22d4fdda3bba

I am also working on BruTile to let it always read the available tiles so that the returned null values do not occur in regular cases. Also the schema extent is set to the extent that is actually available so that a client can zoom to that area directly.

**Comment by pauldendulk** [comment] 2017-04-02 11:36
Now BruTile was also updated. The MbTiles sample zooms directly to the MbTiles' extent if you remove the bing baselayer.

**Comment by 88madri** [comment] 2017-04-03 11:47
Hi. I'm updating my project in order to apply this changes. But when I load el-molar.mbtiles I see a different behaviour (I suppose this happens with all the MbTiles) You can see on this two images the new and old behaviour

![oldmapsuibehaviour](https://cloud.githubusercontent.com/assets/17722229/24607838/fa96b396-1873-11e7-80eb-1f798a290c33.png)

![newmapsuibehaviour](https://cloud.githubusercontent.com/assets/17722229/24607847/fe495b92-1873-11e7-916e-d472e29d5840.jpg)


Is this a setting or option??

**Comment by pauldendulk** [comment] 2017-04-03 16:54
I am not sure how this would be affected by the recent changes. I wonder if the previous behavior was correct. 

I do understand there should be some kind of clipping. The tiles cover a broader extent than the extent of el-molar. You would want to clip to the el-molar extent. But this was not implemented in the previous version either. So, I am not quite sure what caused what you see there.

**Comment by 88madri** [comment] 2017-04-03 18:32
Sorry. The first one is the old behaviour (the one I want) and the second is the new behaviour. 
So I don't know exactly was its going on here. it seems that with the update if the mbtile does not have tile for that zoom level the Map load a blank Tile... or something like that instead of leaving the old one zoomed.

**Comment by pauldendulk** [comment] 2017-04-03 20:47
ok, I think I understand. In the new situation the MbTiles schema has the extent of the region specified in the MbTiles metadata. Because the TileLayer now knows the extent it tried to fetch only the tiles covering the extent. 

The only thing I would like to improve here is that you limit the part that is actually drawn to the specified extent. So this would make the visible part a lot smaller.

What you saw in the old situation is that the extent was set to the whole world and the TileLayer tried to fetch all tiles covering the map. When a tile is not found for a resolution it tries to find a tile above it (in the tile pyramid). Those are the blurry tiles that you see top right.

I wonder if this is what you should want. I think you should be able to reproduce this again if you pass the full world extent to MbTilesTileSource constructor but it looks like there is a bug in the constructor. I have to check that later.

Perhaps there are better alternative. Maybe you should include a global (or spanish) mbtiles file with just the top layers as a background layer. Or maybe panning should be restricted to just the extent of the el molar mbtiles.

**Comment by 88madri** [comment] 2017-04-04 06:24
Yeah, I'm trying change the schema with 

```
var mbTilesTileSource = new MbTilesTileSource(new SQLiteConnectionString(pathToFile, true),
                    new GlobalSphericalMercator(yAxis: YAxis.TMS, extent: new Extent(-20037508.342789, -20037508.342789, 20037508.342789, 20037508.342789)));

```

But the Map is always blank, I cannot obtain the Tiles.

**Comment by pauldendulk** [comment] 2017-04-04 06:54
It is a bug in mbtilestilesource. It has an internal tilerange which is not initialized with the schema in the constructor.

**Comment by 88madri** [comment] 2017-04-04 06:58
Also, the molar.mbtiles has the top layer complete (I mean the whole world), I don't know why the layer envelope only goes to -400542.396751338,4967160.12544783 -387716.263405087,4974605.09200281.
instead of the whole world Extent.

**Comment by pauldendulk** [comment] 2017-04-04 07:20
That extent is the extent for which the mbtiles was created. The person who created this mbtiles (you?) has specified this in some way. The bug in mbtilestilesource should be fixed but I still think what you want is not a good idea. The extra top tiles that you want are there by chance. The only area that is covered for sure is that small extent. Everything outside that area is there because tiles happen to cover a larger area. The way this works out depends on the tileschema and can result in weird results in other situations. I understand you want some context for your mbtiles, but that should be done in another way.

**Comment by 88madri** [comment] 2017-04-04 07:41
I understand, If I changed the bounds property of elmolar.btile to the whole world then it works as before.
It was a fault because the mbtiles covers world from level 0. 
Thanks Paul :)

**Comment by pauldendulk** [comment] 2017-04-04 08:22
ah, you edited the database itself, did not think of that. good workaround.
