### ISSUE TITLE
Center alignment of labels is off for some strings

### ISSUE THREAD

**Issue by spaddlewit** [pauldendulk/Mapsui#209] opened 2017-07-04 17:29 UTC
Try it with a label text of '11CD'.

Affects Skia only

**Comment by spaddlewit** [comment] 2017-07-08 17:55
My pull request reduces the problem, but it still doesn't seem to fix it entirely. I will try to create a repro project.

**Comment by pauldendulk** [comment] 2017-07-08 19:38
The problem could also be caused by the fact that it is drawn as bitmap first. We could also try to draw directly on canvas to see if this fixes it. The bitmap is for performance and I think will be necessary.

**Comment by spaddlewit** [comment] 2017-07-08 20:07
Yeah, definitely need the performance -- not getting great results, currently. Despite my pull request, the issue seems to still persist on point layers that have labels of varying font size... so the bitmap caching might not be remeasuring each individual label properly??

**Comment by pauldendulk** [comment] 2017-07-09 06:21
What I was thinking is that the extra step of first caching causes some rounding error. 

I don't know yet what problem you see. Could you post a screen shot? You can just copy-paste in github comments.

**Comment by pauldendulk** [comment] 2017-07-09 07:20
I just update the Skia version and it seems it improves the labels https://github.com/pauldendulk/Mapsui/issues/205. Could you check if this improves it in your case?

**Comment by spaddlewit** [comment] 2017-07-09 14:56
Here's a screenshot of the problem using my pull requests. Without the pull requests on 1.0.9, it is even more off-center.

These points are on a single layer, with varying LabelStyles. Both LabelStyles have horizontal and vertical alignment set to center. The symbols are bitmaps, however I also tried using the built-in circle and square symbols and got the same result.

![image](https://user-images.githubusercontent.com/29378443/27994983-3c62115e-6495-11e7-8f1c-355d4ba22a77.png)

**Comment by spaddlewit** [comment] 2017-07-09 15:43
Using 1.0.10, this is what I get. It's better, but still not quite there. The vertical centering looks to be fixed:

![image](https://user-images.githubusercontent.com/29378443/27995394-aa3da606-649b-11e7-8a00-d4cafed95d32.png)

**Comment by charlenni** [comment] 2017-07-10 07:36
Could it be, that this problem exists, because you use a monospaced font (https://en.wikipedia.org/wiki/Monospaced_font)? Labels with a "1" seem to get worther than that with a "2" or "3", which are both widther than a "1".

**Comment by pauldendulk** [comment] 2017-07-10 09:42
@charlenni The size SKPaint.MeasureText should take into account the font. So this should be correct. Could be a bug in SkiaSharp though.

**Comment by pauldendulk** [comment] 2017-07-10 09:46
@spaddlewit Perhaps the images are not the correct size. The 12C top-left, for instance, may have part of the bitmap before the 1. This could be checked by setting a background color for the bitmap. 

The result of MeasureText is more complicated than I initially expected. Perhaps I did not interpret it correctly.

**Comment by charlenni** [comment] 2017-07-10 10:00
Your last answer was, what I assume. There are empty space before the "1", which is transparent, while the characters often use the whole size.

The idea with background color is very good to test this. Or drawing a rect instead of text with calculated width and height.

**Comment by pauldendulk** [comment] 2017-07-10 10:11
@charlenni Yes, that is what I meant.

**Comment by spaddlewit** [comment] 2017-07-10 11:40
The images are 32x32, and they take up the entire space of the image. I also tried this with the built-in Rectangle and Ellipse symbols, and it looks exactly the same. I'll set a background image and try to get you some screenshots.

**Comment by pauldendulk** [comment] 2017-07-10 21:33
@spaddlewit What font do you use?

**Comment by pauldendulk** [comment] 2017-07-10 21:43
I committed something what I think should fix it. Is it easy for you to check this without the new nuget package?

**Comment by spaddlewit** [comment] 2017-07-10 21:55
Verdana.
Maybe -- is there a way I can merge the changes you've made since I forked into my own branch? (I'm new to GitHub... mostly experienced with SVN)

**Comment by pauldendulk** [comment] 2017-07-10 22:32
Something like this: https://stackoverflow.com/a/11583019/85325

You could also manually make the change. A single minus is removed. You will have to revert your own changes with respect to this issue though.

**Comment by spaddlewit** [comment] 2017-07-10 23:41
Getting closer.. ohhh so closer... almost not even noticable:

![image](https://user-images.githubusercontent.com/29378443/28044845-c8977b92-65a7-11e7-9290-42eda19ff23b.png)

**Comment by spaddlewit** [comment] 2017-07-10 23:43
As you can see, sometimes the text is still slightly too far to the right (big size), or too far to the left (small size).

Maybe an issue with scaling coordinates relative to the size of the font? Dunno, grasping at straws here.

**Comment by spaddlewit** [comment] 2017-07-10 23:57
Here we go. This demonstrates the problem clearer:

![image](https://user-images.githubusercontent.com/29378443/28045250-f69ce322-65a9-11e7-842d-a02476688670.png)

**Comment by spaddlewit** [comment] 2017-07-11 00:06
And just to prove it's not the bitmap... Here it is, using the built-in Rectangle SymbolStyle:

![image](https://user-images.githubusercontent.com/29378443/28045467-40dd33dc-65ab-11e7-8b8b-9da175a94372.png)

**Comment by pauldendulk** [comment] 2017-07-11 06:46
The picture clearly demonstrates a problem. It is not what I see with the samples in master. I would say they are not more than one pixel off. Font size also does not seem to affect my sample like yours.

In your repository the minus in ```var backRectXOffset = -rect.Left;``` is still there: https://github.com/spaddlewit/Mapsui/blob/f64388e4c0a20b26ae0d29049387cd81970a9ba4/Mapsui.Rendering.Skia-PCL/LabelRenderer.cs, but perhaps you fixed that locally.

**Comment by spaddlewit** [comment] 2017-07-11 11:11
Yeah, I fixed it locally, since I found it easier to just edit that instead.
What I'll do next is see if I can spin up a sample project that easily reproduces the problem, so you can try it yourself and experiment with fixes.

**Comment by pauldendulk** [comment] 2017-07-11 11:45
Yes, that will be great.

**Comment by spaddlewit** [comment] 2017-07-11 18:53
here you go, this is a modification of the Label sample:

        public static ILayer CreateLayer()
        {
            var memoryProvider = new MemoryProvider();

            var featureWithDefaultStyle = new Feature {Geometry = new Point(0, 0)};
            featureWithDefaultStyle.Styles.Add(new LabelStyle { Text = "Default Label" });
            memoryProvider.Features.Add(featureWithDefaultStyle);

            var featureWithBottomAlignedStyle = new Feature { Geometry = new Point(0, -4000000) };
            featureWithBottomAlignedStyle.Styles.Add(new LabelStyle
            {
                Text = "11C",
                Font = new Font { FontFamily = "Verdana", Size = 24 },
                BackColor = null,
                VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Center,
                HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Center,
            });
            memoryProvider.Features.Add(featureWithBottomAlignedStyle);

            var featureWithRightAlignedStyle = new Feature { Geometry = new Point(1121120, -2000000) };
            featureWithRightAlignedStyle.Styles.Clear();
            featureWithRightAlignedStyle.Styles.Add(new SymbolStyle { SymbolType = SymbolType.Ellipse, SymbolScale = 0.75, Fill = new Brush(Color.Green) });
            featureWithRightAlignedStyle.Styles.Add(new LabelStyle
            {
                Text = "4B",
                Font = new Font { FontFamily = "Verdana", Size = 12 },
                BackColor = null,
                VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Center,
                HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Center,
            });
            memoryProvider.Features.Add(featureWithRightAlignedStyle);


            var featureWithColors = new Feature {Geometry = new Point(0, -6000000)};
            featureWithColors.Styles.Add(CreateColoredLabelStyle());
            memoryProvider.Features.Add(featureWithColors);

            return new MemoryLayer {Name = "Points with labels", DataSource = memoryProvider};
        }

**Comment by pauldendulk** [comment] 2017-07-11 19:30
Thanks! I could paste that right in my sample

**Comment by pauldendulk** [comment] 2017-07-11 19:33
When I run it it looks okay to me. It is displace wrt wpf by one pixel at the most. Could it be your project was not fully updated to the latest SkiaSharp? You could try checkout my project and paste your code into it. Don't you see the same as this:

![image](https://user-images.githubusercontent.com/963462/28086811-7ee56ba6-6680-11e7-9cbd-3ee54465a98c.png)

**Comment by spaddlewit** [comment] 2017-07-11 19:43
Yep, that's the same result I get in the sample. It's possible that Skia was not updated on the iOS project, where I took the screenshots from.. It's getting a bit unweidly having all of these DLLs flying around. I need the halo in Skia, so I'm having to jump back and forth between NuGets and custom built DLLs.

That aside, it does still look slightly off, but this may be due to text measuring in Skia *still* not being completely correct.

**Comment by pauldendulk** [comment] 2017-07-11 19:59
With an error this small it becomes too hard for me to determine what is right and what is wrong. Please check if you can fix your own project if you create a new fork. Also, it could be something in iOS. I only use WPF to test Skia.

**Comment by spaddlewit** [comment] 2017-07-11 20:20
Gotcha. I'll clean things up in the next day or so and report back. Thanks for merging the halo stuff... that'll make it easier to go back to 100% NuGets and ensure the versions are correct.

**Comment by pauldendulk** [comment] 2017-07-17 16:11
Considering this fixed for now.

**Closed by pauldendulk** 2017-07-17 16:11 UTC
Labels: bug

**Comment by spaddlewit** [comment] 2017-07-17 16:32
Sounds good. Haven't had time to test. Will let you know if it persists.
