### ISSUE TITLE
Map refreshes when adding a new layer but not when removing it.

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#246] opened 2017-11-10 14:12 UTC
I'm using WPF MapControl. And I'm working with the MapLayers (MapControl.Map.Layer) 
When I add a new layer the map appears with the new layer but when I remove it the map does not update. Thanks.

**Comment by pauldendulk** [comment] 2017-11-10 14:34
After removing the layer you could call MyMapControl.Refresh(). It probably makes sense to trigger a refresh from the LayerRemoved event.

**Comment by pauldendulk** [comment] 2017-12-15 15:06
Fixed in https://github.com/pauldendulk/Mapsui/releases/tag/1.2.0

**Closed by pauldendulk** 2017-12-15 15:06 UTC
Labels: enhancement

**Comment by Skymirrh** [comment] 2017-12-17 15:04
Sorry to bother you, but where is the code fixing this? I have tried looking up the history and [comparing trees between 1.1.3 and 1.2.0](https://github.com/pauldendulk/Mapsui/compare/1.1.3...1.2.0) but couldn't figure out how this was fixed.

**Comment by pauldendulk** [comment] 2017-12-17 17:16
I had rewritten some of the logic for the rendering loop for the widget
rendering. Then tested this issue. Could not reproduce it. Assumed it fixed
and closed it. Perhaps to enthoustic. Please reopen if needed.

Op 17 dec. 2017 4:04 p.m. schreef "Skymirrh" <notifications@github.com>:
