### ISSUE TITLE
Anti aliasing issue with UWP and display scaling > 100%

### ISSUE THREAD

**Issue by NOTAPIYC** [pauldendulk/Mapsui#345] opened 2018-03-15 19:08 UTC
Hi!
First of all I am sorry if this is the wrong place to ask this question, but this problem has been bugging me for a while. I am new to this entire topic, so there may already be a solution, that I am just not seeing.

I tried to replicate the UWP sample with this line of code:

`MapControl.Map.Layers.Add(OpenStreetMap.CreateTileLayer());`

It works like a charm, however my map will look pixelated when display scaling is set to greater than 100% in the Windows settings. This looks like an anti aliasing problem. See the effect in this comparison (left is OSM in my browser, right is OSM in my UWP app):

![mapsui_anti_aliasing](https://user-images.githubusercontent.com/37417517/37484965-65b75924-288a-11e8-8739-5b0f64001965.PNG)

Display scaling is set to 125%. It will get worse if I increase this value. Is there a way to fix this? Am I missing some rendering function? I browsed through the samples of Mapsui and BruTile but could not find a hint to a solution. If it is something to fix on the UWP side, is there some experience with this? I searched the net with no result.

**Comment by pauldendulk** [comment] 2018-03-16 07:39
This the right place to ask this questions, although good answers are not guaranteed :).

If you change display scaling does this affect osm in the browser at all? 
If you set display scaling to 100% are the browser and Mapsui nearly identical?

Perhaps we should take some system variable into account to counter this problem. Although the purpose of setting display scaling is to enlarge the fonts, so perhaps this is what some people want. 

Anti aliasing is probably not the issue since the labels seen there are part of the image tiles. The images are enlarged though, which make it blocky.

**Comment by charlenni** [comment] 2018-03-16 12:00
I assume, that the problem is, that you compare a vector map (OSM) with a bitmap map. Mapsui gets a bitmap and scales this, OSM uses vectors and draws the map new each time with the correct scaling.

**Comment by pauldendulk** [comment] 2018-03-16 12:06
openstreetmap.org still uses bitmap tiles. They are the same tiles as in the map. They just don't scale up with display scaling.

**Comment by NOTAPIYC** [comment] 2018-03-17 11:40
Thanks! Yes, if set to 100%, OSM in my UWP app looks basically identical to the OSM within the browser. The images at the same zoom level within the browser also enlarge when increasing display scaling, however without loosing quality.

The current display scaling can be accessed on Windows by using something like this:

`ResolutionScale resolutionScale DisplayInformation.GetForCurrentView().ResolutionScale;`

This returns an enum, that can be used to calculate a correction factor.

**Comment by pauldendulk** [comment] 2018-04-06 21:31
I tried to replicate this.

Initially I assumed the size at which the tiles were displayed was different but on UWP, WPF and on openstreetmap.org they are exactly the same.

The pixelated look in the screenshot is probably caused by the rendering issue discussed here:
https://github.com/pauldendulk/Mapsui/issues/352
This is something that is now fixed in the version after 1.3.2.

**Closed by pauldendulk** 2018-04-06 21:31 UTC
Labels: question
